return {
  'Intro/Hello_World',
  'Intro/Spinning_Cube',
  'Intro/3D_Model',
  'Intro/360_Photo',
  'Intro/Tracked_Hands',
  'Interaction/Pointing',
  'Custom_Mesh',
  'Animation',
  'Physics',
  'PBR_Materials',
  'Cubemap',
  'Postprocessing',
  'Instancing',
  'Primitives',
  'Spectator_Camera',
  'Microphones',
  'Optimization/Mask'
}
